# Generated by Django 2.1.5 on 2019-09-20 20:48

from django.db import migrations, models
import django.db.models.deletion
import patterndetection.tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_format', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ForegroundFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreground_format', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobcode', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('foreground_data', models.FileField(blank=True, null=True, upload_to=patterndetection.tool.models.unique_filename, verbose_name='Uploaded File')),
                ('context_data', models.FileField(blank=True, null=True, upload_to=patterndetection.tool.models.unique_filename, verbose_name='Uploaded File')),
                ('p_value_cutoff', models.FloatField(default=0.001)),
                ('minimum_occurrences', models.IntegerField(default=2)),
                ('fold_change_cutoff', models.FloatField(default=1.0)),
                ('max_depth', models.IntegerField(blank=True, null=True)),
                ('extend_sequences', models.BooleanField(default=False)),
                ('width', models.IntegerField(default=8)),
                ('center_sequences', models.BooleanField(default=True)),
                ('multiple_testing_correction', models.BooleanField(default=True)),
                ('positional_weighting', models.BooleanField(default=True)),
                ('compound_residues', models.BooleanField(default=True)),
                ('compound_residue_decomposition', models.BooleanField(default=True)),
                ('contextformat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.ContextFormat')),
                ('extension_direction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.ExtensionDirection')),
                ('foregroundformat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.ForegroundFormat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
    ]
