# Generated by Django 2.1.5 on 2019-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='center_sequences',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='compound_residue_decomposition',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='compound_residues',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='extend_sequences',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='fold_change_cutoff',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_occurrences',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='multiple_testing_correction',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='positional_weighting',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='width',
            field=models.IntegerField(blank=True, default=8),
        ),
    ]
