# Generated by Django 2.1.5 on 2019-04-24 22:59

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_format', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to=tool.models.unique_filename, verbose_name='Uploaded File')),
                ('raw_sequences', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_format', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to=tool.models.unique_filename, verbose_name='Uploaded File')),
                ('raw_sequences', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alpha', models.FloatField(default=0.01)),
                ('multiple_testing_correction', models.BooleanField(default=True)),
                ('minimum_occurrences', models.IntegerField(default=2)),
                ('fold_change_cutoff', models.FloatField(default=1)),
                ('expand_peptides', models.BooleanField(default=False)),
                ('center_positions', models.BooleanField(default=True)),
                ('compound_residues', models.BooleanField(default=True)),
                ('position_limit', models.IntegerField(blank=True, null=True)),
                ('positional_weighting', models.BooleanField(default=True)),
                ('ignore_background_positions', models.CharField(blank=True, max_length=120, null=True)),
                ('background_regular_expression', models.CharField(blank=True, max_length=120, null=True)),
                ('backgroundformat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.BackgroundFormat')),
                ('backgroundupload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.BackgroundUpload')),
                ('dataformat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.DataFormat')),
                ('dataupload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.DataUpload')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Job')),
            ],
        ),
        migrations.CreateModel(
            name='ProteomeUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to=tool.models.unique_filename, verbose_name='Uploaded File')),
                ('raw_sequences', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='proteomeupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.ProteomeUpload'),
        ),
        migrations.AddField(
            model_name='job',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
