# Generated by Django 2.1.5 on 2019-04-25 22:12

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='backgroundupload',
            field=models.FileField(blank=True, null=True, upload_to=tool.models.unique_filename, verbose_name='Uploaded File'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dataupload',
            field=models.FileField(blank=True, null=True, upload_to=tool.models.unique_filename, verbose_name='Uploaded File'),
        ),
        migrations.AlterField(
            model_name='job',
            name='proteomeupload',
            field=models.FileField(blank=True, null=True, upload_to=tool.models.unique_filename, verbose_name='Uploaded File'),
        ),
    ]
