# Generated by Django 2.1.5 on 2019-04-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20190425_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcode', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
