# Generated by Django 2.1.5 on 2019-05-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_queuetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.FileField(upload_to='')),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FigureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logomap', models.FileField(upload_to='')),
                ('sequences', models.FileField(upload_to='')),
                ('pattern_string', models.CharField(max_length=120)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BackgroundUpload',
        ),
        migrations.DeleteModel(
            name='DataUpload',
        ),
        migrations.RemoveField(
            model_name='output',
            name='job',
        ),
        migrations.DeleteModel(
            name='ProteomeUpload',
        ),
        migrations.DeleteModel(
            name='QueueTest',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='jobcode',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.AddField(
            model_name='patterns',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Job'),
        ),
        migrations.AddField(
            model_name='figures',
            name='figuretype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.FigureType'),
        ),
        migrations.AddField(
            model_name='figures',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Job'),
        ),
    ]
