# Generated by Django 2.1.5 on 2019-05-06 20:01

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20190506_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figures',
            name='data',
            field=models.FileField(upload_to=tool.models.unique_filename),
        ),
        migrations.AlterField(
            model_name='figures',
            name='figure',
            field=models.FileField(upload_to=tool.models.unique_filename),
        ),
    ]
